/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HelloJavaGradle;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Consumer consumer = new Consumer();
        consumer.setName("First Kafka Consumer");
        String name = consumer.getName();

        System.out.println("name = " + name);
    }
}
